### ISSUE TITLE
Other injected bean don't work?

### ISSUE THREAD

**Issue by tdudgeon** [coders-kitchen/WeldSE-Example#1]
Correct me if I'm wrong, but this only seems to work for the BootLoader class.
If from that class I create a new bean that uses @Inject then the right stuff is not injected.

e.g if in the BootLoader.bootListener() method I add this:

Bean bean = new Bean();
System.out.println("Worker: " + bean.getWorker());

where Bean has the worker @Injected-ed then I get a null worker.

Am I missing something?

Tim

**Comment by coders-kitchen** [comment]
Hi!

From the snippet you mentioned, I see that you try to do something like this

```
public class Bean {
  @Inject
  Worker w;

  Worker getWorker() {
    return w;
  }
}

public class BootLoader {
  public void bootListener(@Observes ContainerInitialized event, @Parameters List<String> cmdLineArgs) {
    Bean bean = new Bean(); // Here is the problematic area
    bean.getWorker().work();
  }
}
```

As pointed out by the inline comment, the problem lies at the place with 

```
Bean bean = new Bean();
```

You bypass here the dependency injection mechanics of WELD / CDI and create a new class of its own. Weld / CDI isn't aware of this and due to this can't inject the Worker bean.

I hope this helps :)

Cheers

Peter

**Comment by tdudgeon** [comment]
Thanks. That makes sense now.
